In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
import pandas as pd
import numpy as np

from google.colab import files

In [ ]:
uploaded = files.upload()

Saving Maintenance_Analytics (1).xlsx to Maintenance_Analytics (1) (1).xlsx

In [ ]:
file_name = list(uploaded.keys())[0]

print(file_name)

Maintenance_Analytics (1) (1).xlsx

In [ ]:
excel = pd.ExcelFile(file_name)

print(excel.sheet_names)

['Cases', 'Spare Parts', 'Replacement']

In [ ]:
cases = pd.read_excel(
    file_name,
    sheet_name="Cases"
)

SpareParts= pd.read_excel(
    file_name,
    sheet_name="Spare Parts"
)

replacement = pd.read_excel(
    file_name,
    sheet_name="Replacement"
)

In [ ]:
cases.head()

,Casenumber,Work Orders Type,Warranty Status,Tr warranty date,Government,Central Telephone,LSC Branch,Model,Status Reason,Product type,...,second Model,Final Brand,Product Barcode,14/30 Days,Defect Major,Epidemic Or Non Epidemic,Industrial,Non Industrial - Improvement Plan,local/ Import,Count of Casenumber
0,CN0000001,Workshop,In Warranty,2025-01-30,Suez,Canal Call Center,LSC - Nasr City,SKY-10OI43,Pending Customer,LED TV,...,NaN,Skyworth,6542351161559,Within 14 Days,Minor,Non Epidemic,Non Industrial,Yes,Import,1
1,CN0000002,Home Visit,Out of Warranty,2025-07-16,Sohag,Delta Call Center,LSC - Ismailia,HIS-86LR37,Closed - Unresolved,No Frost,...,NaN,Hisense,7648350305641,After 30 Days,Major,Non Epidemic,Non Industrial,No,Local,1
2,CN0000003,Workshop,Out of Warranty,2024-06-29,Suez,Upper Egypt Call Center,LSC - Mohandessin,SKY-59CQ31,Open,Direct Cool,...,NaN,Skyworth,7848018451462,After 30 Days,Minor,Epidemic,Non Industrial,No,Import,1
3,CN0000004,Home Visit,Extended Warranty,2025-07-11,Assiut,Delta Call Center,LSC - Mansoura,SON-19UP28,Open,Split AC,...,NaN,Sony,8248963834657,After 30 Days,Cosmetic,Non Epidemic,Non Industrial,Yes,Local,1
4,CN0000005,Workshop,In Warranty,2025-01-24,Ismailia,Alexandria Call Center,LSC - Damanhour,BEK-96XO96,Cancelled,Convection,...,NaN,Beko,106513338726,After 30 Days,Major,Non Epidemic,Non Industrial,Yes,Local,1

In [ ]:
SpareParts.head()

,Case Number,government,Central Telephon,created on(Case),Spare Part,Actual Model 1(case),Actual Model 2(case),brand 1(case),brand(case),Model TR(case),...,sap return,Account,Defectcode count,TR Warranty Status,خامات,Quantity,Price,Total price,Spare part Warranty,Count of Case Number
0,CN0002525,New Valley,Upper Egypt Call Center,2026-08-14,LED Strip,TOS-84VL38,NaN,Toshiba,Toshiba,TOS-84VL38,...,No,LSC - Alexandria,3,Out of Warranty,LED Strip,1,145.67,145.67,6 Months,1
1,CN0003381,Damietta,Alexandria Call Center,2025-01-06,Sensor,SKY-23FR68,NaN,Skyworth,Skyworth,SKY-23FR68,...,No,LSC - Tanta,1,Out of Warranty,Sensor,1,35.92,35.92,12 Months,1
2,CN0004486,Qalyubia,Upper Egypt Call Center,2025-11-05,LED Strip,HIS-22KX03,NaN,Hisense,Hisense,HIS-22KX03,...,No,LSC - Mansoura,1,Extended Warranty,LED Strip,1,217.30,217.30,6 Months,1
3,CN0003618,Sharqia,Canal Call Center,2026-03-03,Power Board,HIS-98SO48,HIS-68QH14,Hisense,Hisense,HIS-98SO48,...,No,LSC - Alexandria,1,Out of Warranty,Power Board,2,645.03,1290.06,6 Months,1
4,CN0000395,Alexandria,Cairo Call Center,2025-07-25,Sensor,BEK-27BF06,NaN,Beko,Beko,BEK-27BF06,...,No,LSC - Sohag,2,Extended Warranty,Sensor,1,71.26,71.26,12 Months,1

In [ ]:
replacement.head()

,Sales Document,Purchase order number,Created on,Family,Material,Actual Model 1 (Regarding) (Case),Product,Product Final,Brand,Source,...,Replacement AC,Problem,Problem2,Problem3,Created From (Regarding) (Case),Resource (Regarding) (Case),Resource Last Comment (Regarding) (Case),Centeral,Discount-TL,Count Of Rep.
0,SD8279999,PO398257,2026-01-06,Home Appliances,MAT-62254,HIS-33XW22,Window AC,Window AC,Hisense,Legal Case,...,Yes,Restart,NaN,NaN,Web Portal,Katie Choi,Technician visit scheduled.,Delta Call Center,12.65,1
1,SD3843557,PO136103,2026-04-22,Home Appliances,MAT-70759,BEK-92CC35,Direct Cool,Direct Cool,Beko,Warranty Claim,...,No,Display Error,NaN,NaN,Social Media,Carl Crawford,Unit repaired on first visit.,Upper Egypt Call Center,11.93,1
2,SD3469029,PO882327,2026-02-05,Home Appliances,MAT-83525,TOS-08LY56,LED TV,LED TV,Toshiba,Warranty Claim,...,No,Backlight,Backlight,Water Leakage,Walk-in,Carl Jarvis,Unit repaired on first visit.,Upper Egypt Call Center,13.87,1
3,SD4298912,PO993064,2025-06-21,Home Appliances,MAT-78906,BEK-99KU81,Solo,Solo,Beko,Warranty Claim,...,No,Temperature Issue,NaN,NaN,Web Portal,Michael Boyer,Waiting on spare part delivery.,Canal Call Center,5.48,1
4,SD9123555,PO560351,2025-08-22,Electronics,MAT-62595,SON-93DA27,Direct Cool,Direct Cool,Sony,Legal Case,...,No,No Picture,Water Leakage,NaN,Web Portal,Russell Gutierrez,Unit repaired on first visit.,Alexandria Call Center,14.96,1

In [ ]:
cases.columns

Index(['Casenumber', 'Work Orders Type', 'Warranty Status', 'Tr warranty date',
       'Government', 'Central Telephone', 'LSC Branch', 'Model',
       'Status Reason', 'Product type', 'Product Group', 'Product-Type',
       'Problem', 'Problem 2', 'Problem 3', 'EndDate order',
       'Defect description', 'Replacement OR Maintenance', 'Serial TR',
       'Second serial', 'StatusReason before followup', 'defect codecount',
       'Created From', 'SAP Number', 'SAP Number LSC', 'Created On order',
       'Resource', 'Resource Last Comment', 'Actual model1', 'Actual Model2',
       'second Model', 'Final Brand', 'Product Barcode', '14/30 Days',
       'Defect Major', 'Epidemic Or Non Epidemic', 'Industrial',
       'Non Industrial - Improvement Plan', 'local/ Import',
       'Count of Casenumber'],
      dtype='object')

In [ ]:
SpareParts.columns

Index(['Case Number', 'government', 'Central Telephon', 'created on(Case)',
       'Spare Part', 'Actual Model 1(case)', 'Actual Model 2(case)',
       'brand 1(case)', 'brand(case)', 'Model TR(case)',
       'technicalserialnumber', 'secondtechnicalserial', 'product G(Case)',
       'product group(Case)', 'product type(case)', 'Work Order Type(case)',
       'Status Reasons( Case)', 'problem 1', 'problem 2', 'problem 3',
       'resource last comment', 'Is Used', 'sap return', 'Account',
       'Defectcode count', 'TR Warranty Status', 'خامات', 'Quantity', 'Price',
       'Total price', 'Spare part Warranty', 'Count of Case Number'],
      dtype='object')

In [ ]:
replacement.columns

Index(['Sales Document', 'Purchase order number', 'Created on', 'Family',
       'Material', 'Actual Model 1 (Regarding) (Case)', 'Product',
       'Product Final', 'Brand', 'Source', 'LCD Inch', 'HT Size', 'HT Type',
       'Description', 'Replacement Type (Regarding) (Work Order)',
       'Government', 'Created on.1', 'Date - Month', 'Serial Number TR',
       'Replacement Defects (Regarding) (Case)', 'Major Defect', 'Sub Defect',
       'Defect Module', 'Root Cause of Replacement (NEW RC )',
       'Last Root Cause Of Replacement', 'TS Note', 'Replacement AC',
       'Problem', 'Problem2', 'Problem3', 'Created From (Regarding) (Case)',
       'Resource (Regarding) (Case)',
       'Resource Last Comment (Regarding) (Case)', 'Centeral', 'Discount-TL',
       'Count Of Rep.'],
      dtype='object')

In [ ]:
print("Cases Shape:")
print(cases.shape)

print("\nSpare Parts Shape:")
print(SpareParts.shape)

print("\nReplacement Shape:")
print(replacement.shape)

Cases Shape:
(5000, 40)

Spare Parts Shape:
(3000, 32)

Replacement Shape:
(1000, 36)

In [ ]:
cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 40 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Casenumber                         5000 non-null   object
 1   Work Orders Type                   5000 non-null   object
 2   Warranty Status                    5000 non-null   object
 3   Tr warranty date                   5000 non-null   datetime64[ns]
 4   Government                         5000 non-null   object
 5   Central Telephone                  5000 non-null   object
 6   LSC Branch                         5000 non-null   object
 7   Model                              5000 non-null   object
 8   Status Reason                      5000 non-null   object
 9   Product type                       5000 non-null   object
 10  Product Group                      5000 non-null   object
 11  Product-Type                       5000 non-null   object
 12  Problem                            5000 non-null   object
 13  Problem 2                          1978 non-null   object
 14  Problem 3                          1016 non-null   object
 15  EndDate order                      5000 non-null   datetime64[ns]
 16  Defect description                 5000 non-null   object
 17  Replacement OR Maintenance         5000 non-null   object
 18  Serial TR                          5000 non-null   object
 19  Second serial                      1770 non-null   object
 20  StatusReason before followup       5000 non-null   object
 21  defect codecount                   5000 non-null   int64
 22  Created From                       5000 non-null   object
 23  SAP Number                         5000 non-null   object
 24  SAP Number LSC                     5000 non-null   object
 25  Created On order                   5000 non-null   datetime64[ns]
 26  Resource                           5000 non-null   object
 27  Resource Last Comment              5000 non-null   object
 28  Actual model1                      5000 non-null   object
 29  Actual Model2                      758 non-null    object
 30  second Model                       412 non-null    object
 31  Final Brand                        5000 non-null   object
 32  Product Barcode                    5000 non-null   int64
 33  14/30 Days                         5000 non-null   object
 34  Defect Major                       5000 non-null   object
 35  Epidemic Or Non Epidemic           5000 non-null   object
 36  Industrial                         5000 non-null   object
 37  Non Industrial - Improvement Plan  5000 non-null   object
 38  local/ Import                      5000 non-null   object
 39  Count of Casenumber                5000 non-null   int64
dtypes: datetime64[ns](3), int64(3), object(34)
memory usage: 1.5+ MB

In [ ]:
SpareParts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Case Number            3000 non-null   object
 1   government             3000 non-null   object
 2   Central Telephon       3000 non-null   object
 3   created on(Case)       3000 non-null   datetime64[ns]
 4   Spare Part             3000 non-null   object
 5   Actual Model 1(case)   3000 non-null   object
 6   Actual Model 2(case)   417 non-null    object
 7   brand 1(case)          3000 non-null   object
 8   brand(case)            3000 non-null   object
 9   Model TR(case)         3000 non-null   object
 10  technicalserialnumber  3000 non-null   object
 11  secondtechnicalserial  1084 non-null   object
 12  product G(Case)        3000 non-null   object
 13  product group(Case)    3000 non-null   object
 14  product type(case)     3000 non-null   object
 15  Work Order Type(case)  3000 non-null   object
 16  Status Reasons( Case)  3000 non-null   object
 17  problem 1              3000 non-null   object
 18  problem 2              1145 non-null   object
 19  problem 3              614 non-null    object
 20  resource last comment  3000 non-null   object
 21  Is Used                3000 non-null   object
 22  sap return             3000 non-null   object
 23  Account                3000 non-null   object
 24  Defectcode count       3000 non-null   int64
 25  TR Warranty Status     3000 non-null   object
 26  خامات                  3000 non-null   object
 27  Quantity               3000 non-null   int64
 28  Price                  3000 non-null   float64
 29  Total price            3000 non-null   float64
 30  Spare part Warranty    3000 non-null   object
 31  Count of Case Number   3000 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(26)
memory usage: 750.1+ KB

In [ ]:
replacement.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 36 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Sales Document                             1000 non-null   object
 1   Purchase order number                      1000 non-null   object
 2   Created on                                 1000 non-null   datetime64[ns]
 3   Family                                     1000 non-null   object
 4   Material                                   1000 non-null   object
 5   Actual Model 1 (Regarding) (Case)          1000 non-null   object
 6   Product                                    1000 non-null   object
 7   Product Final                              1000 non-null   object
 8   Brand                                      1000 non-null   object
 9   Source                                     1000 non-null   object
 10  LCD Inch                                   145 non-null    object
 11  HT Size                                    145 non-null    object
 12  HT Type                                    127 non-null    object
 13  Description                                1000 non-null   object
 14  Replacement Type (Regarding) (Work Order)  1000 non-null   object
 15  Government                                 1000 non-null   object
 16  Created on.1                               1000 non-null   datetime64[ns]
 17  Date - Month                               1000 non-null   object
 18  Serial Number TR                           1000 non-null   object
 19  Replacement Defects (Regarding) (Case)     1000 non-null   object
 20  Major Defect                               1000 non-null   object
 21  Sub Defect                                 1000 non-null   object
 22  Defect Module                              1000 non-null   object
 23  Root Cause of Replacement (NEW RC )        1000 non-null   object
 24  Last Root Cause Of Replacement             1000 non-null   object
 25  TS Note                                    1000 non-null   object
 26  Replacement AC                             1000 non-null   object
 27  Problem                                    1000 non-null   object
 28  Problem2                                   389 non-null    object
 29  Problem3                                   193 non-null    object
 30  Created From (Regarding) (Case)            1000 non-null   object
 31  Resource (Regarding) (Case)                1000 non-null   object
 32  Resource Last Comment (Regarding) (Case)   1000 non-null   object
 33  Centeral                                   1000 non-null   object
 34  Discount-TL                                1000 non-null   float64
 35  Count Of Rep.                              1000 non-null   int64
dtypes: datetime64[ns](2), float64(1), int64(1), object(32)
memory usage: 281.4+ KB

In [ ]:
for col in cases.columns:
    print(col)

Casenumber
Work Orders Type
Warranty Status
Tr warranty date
Government
Central Telephone
LSC Branch
Model
Status Reason
Product type
Product Group
Product-Type
Problem
Problem 2
Problem 3
EndDate order
Defect description
Replacement OR Maintenance
Serial TR
Second serial
StatusReason before followup
defect codecount
Created From
SAP Number
SAP Number LSC
Created On order
Resource
Resource Last Comment
Actual model1
Actual Model2
second Model
Final Brand
Product Barcode
14/30 Days
Defect Major
Epidemic Or Non Epidemic
Industrial
Non Industrial - Improvement Plan
local/ Import
Count of Casenumber

In [ ]:
for col in SpareParts.columns:
    print(col)

Case Number
government
Central Telephon
created on(Case)
Spare Part
Actual Model 1(case)
Actual Model 2(case)
brand 1(case)
brand(case)
Model TR(case)
technicalserialnumber
secondtechnicalserial
product G(Case)
product group(Case)
product type(case)
Work Order Type(case)
Status Reasons( Case)
problem 1
problem 2
problem 3
resource last comment
Is Used
sap return
Account
Defectcode count
TR Warranty Status
خامات
Quantity
Price
Total price
Spare part Warranty
Count of Case Number

In [ ]:
for col in replacement.columns:
    print(col)

Sales Document
Purchase order number
Created on
Family
Material
Actual Model 1 (Regarding) (Case)
Product
Product Final
Brand
Source
LCD Inch
HT Size
HT Type
Description
Replacement Type (Regarding) (Work Order)
Government
Created on.1
Date - Month
Serial Number TR
Replacement Defects (Regarding) (Case)
Major Defect
Sub Defect
Defect Module
Root Cause of Replacement (NEW RC )
Last Root Cause Of Replacement
TS Note
Replacement AC
Problem
Problem2
Problem3
Created From (Regarding) (Case)
Resource (Regarding) (Case)
Resource Last Comment (Regarding) (Case)
Centeral
Discount-TL
Count Of Rep.

In [ ]:
[col for col in cases.columns if "case" in col.lower()]

['Casenumber', 'Count of Casenumber']

In [ ]:
[col for col in SpareParts.columns if "case" in col.lower()]

['Case Number',
 'created on(Case)',
 'Actual Model 1(case)',
 'Actual Model 2(case)',
 'brand 1(case)',
 'brand(case)',
 'Model TR(case)',
 'product G(Case)',
 'product group(Case)',
 'product type(case)',
 'Work Order Type(case)',
 'Status Reasons( Case)',
 'Count of Case Number']

In [ ]:
[col for col in replacement.columns if "case" in col.lower()]

['Actual Model 1 (Regarding) (Case)',
 'Replacement Defects (Regarding) (Case)',
 'Created From (Regarding) (Case)',
 'Resource (Regarding) (Case)',
 'Resource Last Comment (Regarding) (Case)']

In [ ]:
[col for col in cases.columns if "date" in col.lower()]

['Tr warranty date', 'EndDate order']

In [ ]:
[col for col in replacement.columns if "date" in col.lower()]

['Date - Month']

In [ ]:
[col for col in cases.columns if "product" in col.lower()]

['Product type', 'Product Group', 'Product-Type', 'Product Barcode']

In [ ]:
[col for col in cases.columns if "model" in col.lower()]

['Model', 'Actual model1', 'Actual Model2', 'second Model']

In [ ]:
[col for col in cases.columns if "model" in col.lower()]

In [ ]:
[col for col in replacement.columns if "product" in col.lower()]

['Product', 'Product Final']

In [ ]:
[col for col in cases.columns if "problem" in col.lower()]

['Problem', 'Problem 2', 'Problem 3']

In [ ]:
[col for col in cases.columns if "engineer" in col.lower()]

[]

In [ ]:
[col for col in cases.columns if "technician" in col.lower()]

[]

In [ ]:
SpareParts.isnull().sum().sort_values(ascending=False)

Actual Model 2(case)     2583
problem 3                2386
secondtechnicalserial    1916
problem 2                1855
created on(Case)            0
Spare Part                  0
Central Telephon            0
Case Number                 0
brand 1(case)               0
brand(case)                 0
Model TR(case)              0
technicalserialnumber       0
product G(Case)             0
product group(Case)         0
Actual Model 1(case)        0
government                  0
Work Order Type(case)       0
product type(case)          0
problem 1                   0
Status Reasons( Case)       0
resource last comment       0
Is Used                     0
sap return                  0
Account                     0
Defectcode count            0
TR Warranty Status          0
خامات                       0
Quantity                    0
Price                       0
Total price                 0
Spare part Warranty         0
Count of Case Number        0
dtype: int64

In [ ]:
replacement.isnull().sum().sort_values(ascending=False)

HT Type                                      873
LCD Inch                                     855
HT Size                                      855
Problem3                                     807
Problem2                                     611
Created on                                     0
Purchase order number                          0
Sales Document                                 0
Family                                         0
Product                                        0
Product Final                                  0
Material                                       0
Brand                                          0
Description                                    0
Replacement Type (Regarding) (Work Order)      0
Government                                     0
Created on.1                                   0
Date - Month                                   0
Source                                         0
Actual Model 1 (Regarding) (Case)              0
Replacement Defects (Regarding) (Case)         0
Serial Number TR                               0
Major Defect                                   0
Sub Defect                                     0
Last Root Cause Of Replacement                 0
TS Note                                        0
Defect Module                                  0
Root Cause of Replacement (NEW RC )            0
Problem                                        0
Replacement AC                                 0
Created From (Regarding) (Case)                0
Resource (Regarding) (Case)                    0
Resource Last Comment (Regarding) (Case)       0
Centeral                                       0
Discount-TL                                    0
Count Of Rep.                                  0
dtype: int64

In [ ]:
duplicate_cases = cases.duplicated(
    subset="Casenumber"
).sum()

print("Duplicate Cases :", duplicate_cases)

Duplicate Cases : 0

In [4]:
duplicate_cases = Case.duplicated(
    subset="Casenumber"
).sum()

print("Duplicate Cases :", duplicate_cases)

NameError: name 'Case' is not defined

In [ ]:
cases.columns

Index(['Casenumber', 'Work Orders Type', 'Warranty Status', 'Tr warranty date',
       'Government', 'Central Telephone', 'LSC Branch', 'Model',
       'Status Reason', 'Product type', 'Product Group', 'Product-Type',
       'Problem', 'Problem 2', 'Problem 3', 'EndDate order',
       'Defect description', 'Replacement OR Maintenance', 'Serial TR',
       'Second serial', 'StatusReason before followup', 'defect codecount',
       'Created From', 'SAP Number', 'SAP Number LSC', 'Created On order',
       'Resource', 'Resource Last Comment', 'Actual model1', 'Actual Model2',
       'second Model', 'Final Brand', 'Product Barcode', '14/30 Days',
       'Defect Major', 'Epidemic Or Non Epidemic', 'Industrial',
       'Non Industrial - Improvement Plan', 'local/ Import',
       'Count of Casenumber'],
      dtype='object')

In [5]:
duplicate_cases = cases.duplicated(subset="Casenumber").sum()

print("Duplicate Cases :", duplicate_cases)

NameError: name 'cases' is not defined

In [6]:
blank_cases = (
    cases["Casenumber"]
    .isna()
    .sum()
)

print(blank_cases)

NameError: name 'cases' is not defined

In [7]:
uploaded = files.upload()

NameError: name 'files' is not defined

In [11]:
cases = pd.read_excel(
    file_name,
    sheet_name="Cases"
)
cases.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Maintenance_Analytics (1) (1).xlsx'

In [12]:
uploaded = files.upload()

NameError: name 'files' is not defined

In [13]:
import pandas as pd
import numpy as np

from google.colab import files

In [14]:
uploaded = files.upload()

Saving Maintenance_Analytics (1).xlsx to Maintenance_Analytics (1).xlsx

In [16]:
duplicate_cases = Cases.duplicated(
    subset="Casenumber"
).sum()

print("Duplicate Cases :", duplicate_cases)

NameError: name 'Cases' is not defined

In [17]:
file_name = list(uploaded.keys())[0]

In [21]:
cases = pd.read_excel(
    file_name,
    sheet_name="Cases"
)

SpareParts = pd.read_excel(
    file_name,
    sheet_name="Spare Parts"
)

replacement = pd.read_excel(
    file_name,
    sheet_name="Replacement"
)

In [23]:
duplicate_cases = cases.duplicated(
    subset="Casenumber"
).sum()

print("Duplicate Cases :", duplicate_cases)

Duplicate Cases : 0

In [24]:
blank_cases = (
    cases["Casenumber"]
    .isna()
    .sum()
)

print(blank_cases)

0

In [25]:
cases.isnull().sum()

Casenumber                              0
Work Orders Type                        0
Warranty Status                         0
Tr warranty date                        0
Government                              0
Central Telephone                       0
LSC Branch                              0
Model                                   0
Status Reason                           0
Product type                            0
Product Group                           0
Product-Type                            0
Problem                                 0
Problem 2                            3022
Problem 3                            3984
EndDate order                           0
Defect description                      0
Replacement OR Maintenance              0
Serial TR                               0
Second serial                        3230
StatusReason before followup            0
defect codecount                        0
Created From                            0
SAP Number                              0
SAP Number LSC                          0
Created On order                        0
Resource                                0
Resource Last Comment                   0
Actual model1                           0
Actual Model2                        4242
second Model                         4588
Final Brand                             0
Product Barcode                         0
14/30 Days                              0
Defect Major                            0
Epidemic Or Non Epidemic                0
Industrial                              0
Non Industrial - Improvement Plan       0
local/ Import                           0
Count of Casenumber                     0
dtype: int64

In [26]:
SpareParts.duplicated().sum()

np.int64(1)

In [27]:
replacement.duplicated().sum()

np.int64(0)

In [28]:
cases["Warranty Status"].value_counts()

Warranty Status
In Warranty          1697
Out of Warranty      1658
Extended Warranty    1645
Name: count, dtype: int64

In [29]:
cases["Government"].value_counts()

Government
Suez              203
Dakahlia          202
Sharqia           201
New Valley        200
Assiut            197
North Sinai       194
Kafr El Sheikh    191
Damietta          190
Gharbia           190
Beheira           189
Cairo             189
Minya             188
South Sinai       188
Qalyubia          188
Port Said         188
Fayoum            186
Giza              186
Aswan             184
Alexandria        181
Luxor             180
Beni Suef         180
Qena              176
Sohag             171
Ismailia          169
Matrouh           167
Red Sea           163
Monufia           159
Name: count, dtype: int64

In [30]:
cases["Product type"].value_counts()

Product type
Split AC       546
Top Load       527
Window AC      506
Front Load     493
No Frost       492
Direct Cool    481
LED TV         348
Convection     344
Grill          328
OLED TV        325
Solo           310
Smart TV       300
Name: count, dtype: int64

In [31]:
cases["EndDate order"].describe()

count                          5000
mean     2025-12-26 17:11:19.680000
min             2025-01-05 00:00:00
25%             2025-07-01 00:00:00
50%             2025-12-23 00:00:00
75%             2026-06-23 00:00:00
max             2026-12-26 00:00:00
Name: EndDate order, dtype: object

In [33]:
missing_cases = SpareParts[
    ~SpareParts["Case Number"].isin(
        cases["Casenumber"]
    )
]

print(len(missing_cases))

0